use_frameworks!

platform :ios, '13.0'

target 'LiMaoBase_Example' do
#  pod 'WuKongBase', :path => '../'
#
#  pod 'Socket.IO-Client-Swift'
#  pod 'SSZipArchive', '~> 2.2.3'
#  pod 'SocketRocket'
#  pod 'Aspects'
#  pod 'ReactiveObjC'
#  pod 'AsyncDisplayKit', :git => 'https://github.com/tangtaoit/AsyncDisplayKit.git'
#  pod 'librlottie', :git => 'https://github.com/tangtaoit/librlottie.git'
#  
#  pod 'YBImageBrowser/NOSD', :git=>'https://github.com/tangtaoit/YBImageBrowser.git'
#  pod 'YYImage/WebP', :git => 'https://github.com/tangtaoit/YYImage.git'
  target 'LiMaoBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
